package com.bhairavnath.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import com.bhairavnath.Repository.BusRepository;
import com.bhairavnath.Repository.UserRepository;
import com.bhairavnath.entity.Bus;

@Controller
@RequestMapping("/admin")
public class AdminController {

    @Autowired
    private BusRepository busRepo;
    @Autowired
    private UserRepository userRepo;

    @GetMapping("/add-bus")
    public String addBusPage(Model model) {
        model.addAttribute("bus", new Bus());
        return "admin-add-bus";
    }

    @PostMapping("/save-bus")
    public String saveBus(@ModelAttribute Bus bus) {
        busRepo.save(bus);
        return "redirect:/admin/add-bus?success";
    }
    @GetMapping("/admin/users")
    public String users(Model model) {
        model.addAttribute("users", userRepo.findAll());
        return "admin-users";
    }

}
