package com.bhairavnath.Repository;
import org.springframework.data.jpa.repository.JpaRepository;

import com.bhairavnath.entity.Booking;

public interface BookingRepository extends JpaRepository<Booking, Integer> {
}
